// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static  FirebaseOptions android = const FirebaseOptions(
    apiKey: 'AIzaSyAtcnw9tLlzTaztOSdY4i2bC72w0i2mL6g',
    appId: '1:975549460764:android:e021c7a6de077c1d058ad9',
    messagingSenderId: '975549460764',
    projectId: 'nearyou-b2185',
    storageBucket: 'nearyou-b2185.appspot.com',
  );

  static FirebaseOptions ios = const FirebaseOptions(
    apiKey: 'AIzaSyDeQzG6bnNu-z5JSXWZzplTD663_CBgp5k',
    appId: '1:975549460764:ios:a2df244b26a58d9d058ad9',
    messagingSenderId: '975549460764',
    projectId: 'nearyou-b2185',
    storageBucket: 'nearyou-b2185.appspot.com',
    iosClientId: '975549460764-q2086tki5hmhlb56te5uo9n9epesgt5o.apps.googleusercontent.com',
    iosBundleId: 'com.aranguriapps.nearYou',
  );
}
